### ISSUE TITLE
Tag cloud not working as expected

### ISSUE THREAD

**Issue by mkevenaar** [gep13/gep13#61]
Tag https://www.gep13.co.uk/tags/chocolatey ends at 15th of October 2014, but https://www.gep13.co.uk/blog/what-are-all-the-chocolatey-repositories-for is tagged with chocolatey but not shown in the tags page.

**Comment by gep13** [comment]
@mkevenaar hmm, looks like this is a casing issue...

https://raw.githubusercontent.com/gep13/gep13/master/input/blog/what-are-all-the-chocolatey-repositories-for.md
https://raw.githubusercontent.com/gep13/gep13/master/input/blog/chocolatey-kickstarter-is-now-live.md

i.e. `chocolatey` and `Chocolatey`

**Comment by gep13** [comment]
I should probably go through all the tags and make them lowercase for consistency.

**Comment by gep13** [comment]
@mkevenaar I believe that this has now been corrected.

https://www.gep13.co.uk/tags/chocolatey

Shows many more blog posts now.

**Comment by mkevenaar** [comment]
Seems way better!
